# Generated by Django 5.1.6 on 2025-02-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
    ]
